# Generated by Django 3.2.5 on 2021-08-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='area',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
