# Generated by Django 3.2.5 on 2021-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
