# Generated by Django 3.2.5 on 2021-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_field',
            field=models.ImageField(default='media/image1.jpg', upload_to='media/'),
        ),
    ]
