# Generated by Django 3.2.5 on 2021-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
