# Generated by Django 3.2.5 on 2021-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPlog', '0005_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
